### ISSUE TITLE
树莓派 4b 上无法安装 wireguard

### ISSUE THREAD

**Issue by ArArgon** [1orz/My-action#11]
树莓派 4b 的固件现在已经取消了 wireguard，而 opkg 安装尸又提示内核版本过低.

**Comment by 1orz** [comment]
手里没4b可供测试。一般opkg 内核过低无法安装问题，可以尝试加上

**Comment by ArArgon** [comment]
> 手里没4b可供测试。一般opkg 内核过低无法安装问题，可以尝试opkg加上 --nodeps --force-depends参数

但是 wireguard 现在是内核模块

**Comment by 1orz** [comment]
在下一个版本会尝试修复这个问题。多多留意
