### ISSUE TITLE
lean的内核和官网的不一样

### ISSUE THREAD

**Issue by share18x** [1orz/My-action#14]
设备：树莓派2B
官网软件源内核：5.4.52-1
固件内核：5.4.51
错误：无法安装软件
ip6tables无法使用nat
`Configuring kmod-ipt-nat6.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-nat6:
 *      kernel (= 5.4.52-1-5d03e1b9a6c93a939ae64a45d3c91ab2)
`

**Comment by 1orz** [comment]
我觉得这个问题应该反馈给L大的仓库那边吧？

**Comment by share18x** [comment]
我去那边反馈了
他这样说：你这个是安装的内核模块，不能用这种方法来安装，需要在编译前把这个组件勾上，和固件一起编译才能用。
但是还有很多软件包也安装不上
https://github.com/coolsnowwolf/lede/issues/5207

**Comment by 1orz** [comment]
> 我去那边反馈了
> 他这样说：你这个是安装的内核模块，不能用这种方法来安装，需要在编译前把这个组件勾上，和固件一起编译才能用。
> 但是还有很多软件包也安装不上
> [coolsnowwolf/lede#5207](https://github.com/coolsnowwolf/lede/issues/5207)

下个版本会尝试修复 你想安装kmod-ip6-nat对吧？

**Comment by share18x** [comment]
对的，但是最近试了下，有些软件包也安装不了
`root@Mashiro:~# opkg install kmod-fs-ext4
Installing kmod-fs-ext4 (5.4.52-1) to root...
Downloading https://openwrt.proxy.ustclug.org/snapshots/targets/bcm27xx/bcm2709/packages/kmod-fs-ext4_5.4.52-1_arm_cortex-a7_neon-vfpv4.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-fs-ext4:
 *      kernel (= 5.4.52-1-5d03e1b9a6c93a939ae64a45d3c91ab2)
 * opkg_install_cmd: Cannot install package kmod-fs-ext4.
`

**Comment by gzmud** [comment]
> > 我去那边反馈了
> > 他这样说：你这个是安装的内核模块，不能用这种方法来安装，需要在编译前把这个组件勾上，和固件一起编译才能用。
> > 但是还有很多软件包也安装不上
> > [coolsnowwolf/lede#5207](https://github.com/coolsnowwolf/lede/issues/5207)
> 
> 下个版本会尝试修复 你想安装kmod-ipt-nat6对吧？

①其实供下载的版本里面打包所有的kmod就好了，提供下载的几个设备根本不在乎那点容量。

②建议树莓派版本的建议增加luci-app-dockerman、docker-compose，方便树莓派版本使用docker

③既然都有把下载站搞起来了，建议把编译完成的所有包连同整改repositories也提供下载，并增加url到发行设备的opkg repo中，文件树结构和openwrt的一样，可以更新你的版本。

④建议同时提供imagebuilder、sdk下载，方便有些人自行编译或打包。

以上建议就是占点空间，如果服务器空间够，估计还是挺好的。

**Comment by 1orz** [comment]
感谢各位提出的宝贵意见  近期会有小幅度改动~~多多关注

**Comment by 1orz** [comment]
> > > 我去那边反馈了
> > > 他这样说：你这个是安装的内核模块，不能用这种方法来安装，需要在编译前把这个组件勾上，和固件一起编译才能用。
> > > 但是还有很多软件包也安装不上
> > > [coolsnowwolf/lede#5207](https://github.com/coolsnowwolf/lede/issues/5207)
> > 
> > 
> > 下个版本会尝试修复 你想安装kmod-ipt-nat6对吧？
> 
> ①其实供下载的版本里面打包所有的kmod就好了，提供下载的几个设备根本不在乎那点容量。
> 
> ②建议树莓派版本的建议增加luci-app-dockerman、docker-compose，方便树莓派版本使用docker
> 
> ③既然都有把下载站搞起来了，建议把编译完成的所有包连同整改repositories也提供下载，并增加url到发行设备的opkg repo中，文件树结构和openwrt的一样，可以更新你的版本。
> 
> ④建议同时提供imagebuilder、sdk下载，方便有些人自行编译或打包。
> 
> 以上建议就是占点空间，如果服务器空间够，估计还是挺好的。

① ②可以实现 近日就会改动。

③无法实现的原因：由于国内服务器租赁价格比较高昂。硬件以及带宽有限。本下载站不保证SLA100%可用，若作为opkg的镜像站 势必会加大下载站的负担 。无法提供长期稳定的服务。若需要更新可以直接在下载站下载固件 并进行网页更新。

④无法实现的原因：违背了初衷。固件下载站建立的初衷就是方便懒人/小白/伸手党用户下载。这些群体 的要求就是下载固件和下载ipk包。对ImageBuilder和SDK
毫无兴趣，甚至大部分根本不知道这些是干嘛用的。若真的是想学习如何编译固件早就会自己搭建/编译属于自己的ImageBuilder和SDK，就没我小破站什么事了QAQ

感谢提出的宝贵建议！

**Comment by share18x** [comment]
提个建议，希望能把https://github.com/pymumu/smartdns和https://github.com/tty228/luci-app-serverchan编译进去，这都是很好用的软件包。

**Comment by 1orz** [comment]
> 提个建议，希望能把[smartdns](https://github.com/pymumu/smartdns)和[serverchan](https://github.com/tty228/luci-app-serverchan)编译进去，这都是很好用的软件包。

微信推送和smartdns已经编译进固件中，下载刷入即可使用~另外 现在新增了docker-ce docker-compose 刷入体验吧~
