### ISSUE TITLE
来自恩山，希望添加sofethervpn

### ISSUE THREAD

**Issue by violesea** [1orz/My-action#15]
您好，今天刚刷了您的固件，目前一切很完美。唯一美中不足的是没了我之前一直使用的softethervpn这个插件，麻烦能帮忙添加一下吗？ 或者教教我如何添加也行。

麻烦了

**Comment by 1orz** [comment]
下个版本增加  多多关注

**Comment by violesea** [comment]
> 下个版本增加 多多关注

非常感谢。谢谢
