### ISSUE TITLE
求助：squashfs系列固件支持luci网页升级的问题

### ISSUE THREAD

**Issue by derekling** [1orz/My-action#18]
如题，我解压并上传了img格式的新固件，但总是上传过程中网页报错。
如果不解压上传，则发现更新前后的版本号没有变化
So 麻烦详细说一下正确的无缝升级步骤，谢谢

**Comment by 1orz** [comment]
请问你是x86架构的升级嘛？ 当然是需要解压`***.img.gz`为`*.img`再上传.支持网页升级的前提是，升级前的固件必须是squashfs`，才支持无缝升级保留原有配置。

**Comment by derekling** [comment]
> 请问你是x86架构的升级嘛？ 当然是需要解压`***.img.gz`为`*.img`再上传.支持网页升级的前提是，升级前的固件必须是`squashfs`，才支持无缝升级保留原有配置。

是的 x86的 我解压了根本无法完成上传过程 网页总是404
请问解压是用哪个工具呢 我是mac系统

**Comment by 1orz** [comment]
MacOS解压`.gz`文件 貌似是在终端中使用`gzip -d xxx.img.gz` 我没用过MacOS。不太清楚
