### ISSUE TITLE
AC2100:IPV6故障以及修改LAN设置会无故关闭WiFi硬件

### ISSUE THREAD

**Issue by alextreeo** [1orz/My-action#21]
### IPV6故障：无通信能力

拨号概况中可以查看到已经获得到IPV6地址（同时也确认运营商是提供了IPV6地址服务，前身 Padavan 此功能正常）
![image](https://user-images.githubusercontent.com/55431732/95004998-4b5bfe80-05e2-11eb-9ee7-4adc166c938f.png)

但是在路由器概述中，网络显示IPV6显示未连接。
![image](https://user-images.githubusercontent.com/55431732/95005034-b73e6700-05e2-11eb-9b08-03d146211738.png)

同时家庭设备连接网络后显示IPV6无网络通信能力。
![image](https://user-images.githubusercontent.com/55431732/95005053-db01ad00-05e2-11eb-8ec6-57d7f119bd06.png)

[相关IPV6内部设置，是参照您的介绍文件设置]

###  LAN设置会无故关闭WIFI硬件

在LAN中设置内部IPV6和其他相关设置时候，会导致硬体WiFi设备关闭后无法正常自启动。

总体来说固件稳定性非常好，希望作者能够花一些时间查找一下故障原因，这两个问题有些影响正常的使用。

**Comment by 1orz** [comment]
看样子并没有获取到ipv6地址。 你马赛克的下面看轮廓应该是fe80 这是内网ipv6网段，通常来说 拨号后 如果支持ipv6 会自动的在接口列表中，生成一个IPV6 PD (WAN)这样的接口 ,240c :xxxxxx 这样才是一般情况下的公网IPv6前缀。善用搜索引擎。

**Comment by alextreeo** [comment]
首先感谢您的回复！

个人需要使用IPV6地址服务，暂时切换Padavan固件，配置PPPoE后就获取到公网的IP地址了
![image](https://user-images.githubusercontent.com/55431732/95220966-87f84780-07e6-11eb-9880-d4fac5183a8a.png)
![image](https://user-images.githubusercontent.com/55431732/95221493-03f28f80-07e7-11eb-8ed1-50b83f1a0385.png)

通讯能力也得到恢复。

新版本的Openwrt默认配置就可以获取ipv6地址了，一般来说改WAN配置正常就行，就像你说的那样，而且我尝试新建接口也没有dhcpv6和6to4协议，无法做内部IPV6数据转发。

而且也根据你的固件提示修改了对应的设置（https://down.cloudorz.com/Router/#%E5%90%AF%E7%94%A8IPv6）

**Comment by ArArgon** [comment]
WIFI关闭的问题看上去是上游的 Bug。前几天我手动编译新路由3的 Lean OpenWRT 固件，调整 IPv6 相关的 DHCP 选项后，WIFI硬件也被关闭了. 有线连上后可以强制开启，貌似重启后不受影响. 不过之后多出来几个形如 `apcli0` 的无线中继接口，我猜问题跟这个有关.

不过由于运营商的问题，我这边只能下发到 `/128` 的地址，用 `ip6tables` 做的 NAT，下面的问题我帮不到你.

**Comment by market-garden** [comment]
红米AC2100，刷的最新固件，IPV6按照介绍文件设置了，同样不可用，现象也是这样。

**Comment by lrpli** [comment]
> 红米AC2100，刷的最新固件，IPV6按照介绍文件设置了，同样不可用，现象也是这样。

一样 加一
