### ISSUE TITLE
树莓派4b固件问题

### ISSUE THREAD

**Issue by maxzhang666** [1orz/My-action#3]
aria2的配置页面

对于aria2的运行状态的检测路径是错误的

由于这个版本的aria2集成在服务下了导致检测路径错误

不知道该在哪里反馈问题，就写这吧

`/usr/lib/lua/luci/view/aria2/overview_status.htm`

第二行

`admin/nas/arai2/status`

修改为

`admin/services/aria2/status`

即可正常检测运行状态信息

**Comment by 1orz** [comment]
这个问题建议反馈到https://github.com/coolsnowwolf/lede

或者自己改下zzz-default-settings文件用sed查找替换字符串，提交代码我合并。可以修复。(主要是我懒233)
