### ISSUE TITLE
ShadowSocksR Plus+配置时提示找不到 v2ray，无法启动

### ISSUE THREAD

**Issue by twilightspark1e** [1orz/My-action#54]
在刷入固件之后，ShadowSocksR Plus+无法正常运行，在日志中提示到：
2022-01-24 14:32:15: -----------end------------
2022-01-24 14:32:15: 找不到 v2ray，无法启动...
2022-01-24 14:32:15: ----------start------------
请问有什么解决办法吗？谢谢

**Comment by favtony** [comment]
我也遇到了，装了个kuoruan的v2ray解决了

**Comment by twilightspark1e** [comment]
> 

我装了之后提示的是redir tcp error.restart! 在网上查的结果一个是清除订阅节点然后再导入，另一个是修改subscribe.lua文件的代码，我都试了一遍，但是没什么作用

**Comment by 1orz** [comment]
附上你正在使用的版本，架构。不然我也不知道哪里出了问题

**Comment by favtony** [comment]
> 附上你正在使用的版本，架构。不然我也不知道哪里出了问题

版本是24号晚上下的，不过没环境了🤣，因为折腾了好几个rom，发现小内存不太能顶得住v2ray，已经换了个精简的rom
我路由是红米AC2100

**Comment by 1orz** [comment]
> > 附上你正在使用的版本，架构。不然我也不知道哪里出了问题
> 
> 版本是24号晚上下的，不过没环境了🤣，因为折腾了好几个rom，发现小内存不太能顶得住v2ray，已经换了个精简的rom 我路由是红米AC2100

ac2100性能太弱。做ap还行。跑v2太难了

**Comment by twilightspark1e** [comment]
不好意思之前一直没有看到提醒，给我的Redmi AC2100 刷了各种各样的固件都是有一些奇奇怪怪小问题，找到一个能用的ROM之后，千兆的宽带只能跑600m，看来路由器性能还是偏弱，不太适合折腾，最后还是重新刷回官方的了

**Comment by zqcccc** [comment]
https://github.com/fw876/helloworld/issues/758 好像和这个问题有关系，编译前 `make dirclean` 成功解决问题
