### ISSUE TITLE
Web后台提示“当前站点证书不被信任”

### ISSUE THREAD

**Issue by Tsubamei** [1orz/My-action#55]
![Screenshot_2022-01-27-12-20-58-38_a87fd7db6caa850b517aa6fa9d2fcd0e](https://user-images.githubusercontent.com/61179776/151291620-31fd1568-d686-4517-aa9d-aa6752f7112e.jpg)
使用的树莓派固件和安卓Via浏览器

**Comment by Tsubamei** [comment]
![无标题](https://user-images.githubusercontent.com/61179776/151293656-eba1887e-0d39-45b4-8edc-9ac0643762dd.png)
PC版

**Comment by 1orz** [comment]
在后台uhttp里关闭ssl访问就好了
