### ISSUE TITLE
树莓派修改Config文件超频不生效

### ISSUE THREAD

**Issue by Tsubamei** [1orz/My-action#56]
树莓派修改Boot分区里面的config.txt文件，比如添加arm_freq=1000可实现超频至1000MHz。
这个方法在之前的固件有用，在2022年1月20日固件不起作用。

**Comment by Tsubamei** [comment]
之前固件里有个CPU性能优化调节，在新版本里也没了

**Comment by 1orz** [comment]
会在下个版本加入
