### ISSUE TITLE
默认IP：10.0.0.1 修改为其他IP，比如：192.168.1.1，保存后，重新启动后，又会恢复为：10.0.0.1

### ISSUE THREAD

**Issue by piaoyun** [1orz/My-action#8]
默认IP：10.0.0.1 修改为其他IP，比如：192.168.1.1，保存后，重新启动后，又会恢复为：10.0.0.1

**Comment by 1orz** [comment]
请问使用的哪一个平台那一个版本的固件？

**Comment by piaoyun** [comment]
https://down.cloudorz.com/Router/LEDE/x86_64/Lean/openwrt-x86-64-uefi-gpt-squashfs.img.gz

使用的是这个文件，然后是通过爱快路由器里面的虚拟机安装，磁盘是上传的解压后的：openwrt-x86-64-uefi-gpt-squashfs.img文件作为引用磁盘

虚拟机安装后，修改IP，也能访问到路由器界面，但是只要reboot后，启动好了。IP就恢复默认的：10.0.0.1

![QQ截图20200624141948](https://user-images.githubusercontent.com/3724475/85507988-cbf38200-b625-11ea-8c86-9547ca72dc18.jpg)

**Comment by 1orz** [comment]
目前已知在pve虚拟机下没有这个问题？估计是squashfs类固件引发的问题。请尝试使用ext4类型的固件呢？

**Comment by piaoyun** [comment]
经过测试，原来是爱快路由器虚拟机的这个功能引起呢
半虚拟化模式：开启 (获得更好的I/O性能，需客户机系统支持)

不要开启这个半虚拟化模式，就可以保存IP配置
![QQ截图20200624150039](https://user-images.githubusercontent.com/3724475/85511675-8c2f9900-b62b-11ea-9bf2-f8bf1a3f3e20.jpg)
